# Generated by Django 4.2.5 on 2023-10-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseApps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "App Name",
                    models.CharField(
                        choices=[
                            ("django.contrib.admin", "django.contrib.admin"),
                            ("django.contrib.auth", "django.contrib.auth"),
                            (
                                "django.contrib.contenttypes",
                                "django.contrib.contenttypes",
                            ),
                            ("django.contrib.sessions", "django.contrib.sessions"),
                            ("django.contrib.messages", "django.contrib.messages"),
                            (
                                "django.contrib.staticfiles",
                                "django.contrib.staticfiles",
                            ),
                            ("model_generator", "model_generator"),
                        ],
                        max_length=255,
                    ),
                ),
                ("Model Name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BaseModelGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Field Name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.IntegerField(
                        choices=[(101, "Char Field"), (102, "Integer Field")],
                        default=101,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_generator.baseapps",
                    ),
                ),
            ],
        ),
    ]
