# Generated by Django 4.2.5 on 2023-10-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="App Name")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Model Name")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_generator.baseapp",
                        verbose_name="App",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FieldParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verbose_name",
                    models.CharField(max_length=200, verbose_name="Verbose Name"),
                ),
                ("primary_key", models.BooleanField(verbose_name="Primary Key?")),
                ("unique", models.BooleanField(verbose_name="Unique?")),
                ("max_length", models.IntegerField(verbose_name="Max Length")),
                ("blank", models.BooleanField(verbose_name="Blank?")),
                ("null", models.BooleanField(verbose_name="Nullable?")),
                ("default", models.CharField(max_length=255, verbose_name="Default")),
                ("editable", models.BooleanField(verbose_name="Editable?")),
                ("db_index", models.BooleanField(verbose_name="Db Index?")),
                (
                    "db_column",
                    models.CharField(max_length=255, verbose_name="DB Column Name"),
                ),
                (
                    "db_comment",
                    models.CharField(max_length=255, verbose_name="DB Comment"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Field Name")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (101, "AutoField"),
                            (102, "BigAutoField"),
                            (103, "BigIntegerField"),
                            (104, "BinaryField"),
                            (105, "BooleanField"),
                            (106, "CharField"),
                            (107, "DateField"),
                            (108, "DateTimeField"),
                            (109, "DecimalField"),
                            (110, "DurationField"),
                            (111, "EmailField"),
                            (112, "FileField"),
                            (113, "FilePathField"),
                            (114, "FloatField"),
                            (116, "ImageField"),
                            (117, "IntegerField"),
                            (118, "JSONField"),
                            (119, "PositiveBigIntegerField"),
                            (120, "PositiveIntegerField"),
                            (121, "PositiveSmallIntegerField"),
                            (122, "SlugField"),
                            (123, "SmallAutoField"),
                            (124, "SmallIntegerField"),
                            (125, "TextField"),
                            (126, "TimeField"),
                            (127, "URLField"),
                            (128, "UUIDField"),
                        ],
                        default=106,
                        verbose_name="Field Type",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_fields",
                        to="model_generator.basemodel",
                        verbose_name="Model",
                    ),
                ),
                (
                    "parameters",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_parameters",
                        to="model_generator.fieldparameter",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
