# Generated by Django 4.2.5 on 2023-10-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseapps",
            name="App Name",
            field=models.CharField(
                choices=[("model_generator", "model_generator")], max_length=255
            ),
        ),
    ]
