# Generated by Django 4.2.5 on 2023-10-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("model_generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldparameter",
            name="model_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_parameters",
                to="model_generator.modelfield",
                verbose_name="Model Field",
            ),
        ),
        migrations.AlterField(
            model_name="modelfield",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model_fields",
                to="model_generator.basemodel",
                verbose_name="Model",
            ),
        ),
    ]
